name: Fetch News

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: macos-latest
    env:
      BUILD_TIMESTEMP: ""
    steps:
      - uses: actions/checkout@v3

      - name: Create Timestemp
        run: echo "BUILD_TIMESTEMP=`date`" >> $GITHUB_ENV

      - name: Cache Record
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ env.BUILD_TIMESTEMP }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run
        run: |
          python main.py --debug
